#!/bin/sh

php lichess/console -e=dev -d doctrine:mongodb:data:load
php lichess/console -e=dev -d doctrine:mongodb:schema:create --index
php lichess/console -e=dev -d lichess:generate-proxies
php lichess/console -e=dev -d lichess:generate-hydrators

php lichess/console -e=test -d doctrine:mongodb:data:load
php lichess/console -e=test -d doctrine:mongodb:schema:create --index
