#!/bin/sh

php lichess/console doctrine:mongodb:data:load
php lichess/console doctrine:mongodb:schema:create --index
php lichess/console lichess:generate-proxies
php lichess/console lichess:generate-hydrators

php lichess/console-test doctrine:mongodb:data:load
php lichess/console-test doctrine:mongodb:schema:create --index
