#!/bin/sh

php lichess/console apc:clear --opcode
rm -r lichess/cache/prod/*
php lichess/console-prod lichess:generate-proxies
php lichess/console-prod lichess:generate-hydrators
php lichess/console apc:clear
chmod -R 777 lichess/cache/prod
