#!/usr/bin/env php
<?php

require_once __DIR__.'/LichessKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new LichessKernel('dev', true);

$application = new Application($kernel);
$application->run();
