#!/usr/bin/env php
<?php

require_once __DIR__.'/LichessKernel.php';

use Symfony\Framework\WebBundle\Console\Application;

$kernel = new LichessKernel('test', true);

$application = new Application($kernel);
$application->run();
