#!/usr/bin/env php
<?php

require_once __DIR__.'/LichessKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;

$kernel = new LichessKernel('forum_prod', false);

$application = new Application($kernel);
$application->run();
