#!/usr/bin/env php
<?php

require_once __DIR__.'/bootstrap.php.cache';
require_once __DIR__.'/AppKernel.php';

use Symfony\Bundle\FrameworkBundle\Console\Application;
use Symfony\Component\Console\Input\ArgvInput;
use Bundle\LichessBundle\ConsoleGuardRail;

$input = new ArgvInput();
$env = $input->getParameterOption(array('--env', '-e'), 'dev');
$debug = !$input->hasParameterOption(array('--no-debug', ''));
$guardRail = new ConsoleGuardRail();

if (!$guardRail->isSafe($input, $env)) {
    die('It is not safe to run this command in this environment');
}

$kernel = new AppKernel($env, $debug);
$application = new Application($kernel);
$application->run();
